### ISSUE TITLE
Parabens!!!

### ISSUE THREAD

**Issue by ProgramadorVermelho** [Wilberson-Roberto/project-01-unes-universidade#1]
# Estou começando tambem! achei muito legal!
parabens [Meu Repositorio](github.com/ProgramadorVermelho/)

>Se você poder me ajudar não estou resolver um problema:
não estou conseguindo fazer funcionar o botão no read.me para abrir a aula

**Comment by wilberson-roberto** [comment]
Olá @ProgramadorVermelho amanhã dou uma olhada e vejo como está a situação pra ver se eu consigo te ajudar blz? Boa noite 👍

**Comment by wilberson-roberto** [comment]
@ProgramadorVermelho tentei entrar agora no link do repositório mas não está encontrando a página, me informa qual repositório que é que eu abro pelo seu perfil

**Comment by ProgramadorVermelho** [comment]
ok

**Comment by ProgramadorVermelho** [comment]
[Repositorio](https://github.com/ProgramadorVermelho/Primeiras partes)

**Comment by ProgramadorVermelho** [comment]
[Repositorio](https://github.com/ProgramadorVermelho/PrimeirosPassos)

**Comment by ProgramadorVermelho** [comment]
o github pages só esta pegando o README

**Comment by ProgramadorVermelho** [comment]
[Repositorio](https://github.com/ProgramadorVermelho/Primeiros-Passos)

**Comment by wilberson-roberto** [comment]
Olá dev, olha eu olhei seu arquivo readme e não contem nada, vc fez o push para subir o arquivo para cá? agora outra coisa, observei q vc está fazendo em linguagem markdown e como vc disse q estava iniciando também, eu acho que não seria uma boa ideia começar com markdown mais sim com html e css, pois o markdown não é algo que eu vejo ser desenvolvido em empresas muito menos entre alguns colegas de faculdade que tenho. Talvez num futuro seja mais utilizado...

**Comment by ProgramadorVermelho** [comment]
ola!
###Muito obrigado!
entendi... 
eu vou melhorar meu repositorio e colocar o markdown mais para frente

**Comment by wilberson-roberto** [comment]
Disponha, precisando se eu puder ajudar só mandar um oi
